module.exports={
    entry:'./app/js/entry.js',
    output:{
        path:__dirname,
        filename:'build/bundle.js'
    },
    module:{
        loaders:[
            {
                test:/\.css$/,
                loader:'style!css'
            },
            {
                test:/\.js$/,
                exclude:/node_modules/,
                loader:'babel',
                query:{
                    presets:['react','es2015','stage-2']
                }
            }
        ]
    }
}